# devops/deploy.yml
- name: CI Test Deployment
  hosts: all
  sudo: true
  vars:
    repository: https://github.com/jamescross91/circle-ansible-docker.git
    path: /home/ubuntu
    image: jamescross91/cd-test
  tasks:
    - name: Pull github code
      git: repo={{ repository }}
           dest={{ path }}

    - name: Pull API container
      shell: docker pull {{ image }}

    - name: Start API container
      shell: docker-compose up -d